"""add graduation_year column to resumes

Revision ID: 9575eaa93193
Revises: 5b167c031e2c
Create Date: 2026-09-27 16:41:55.328226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9575eaa93193'
down_revision: Union[str, Sequence[str], None] = '5b167c031e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('graduation_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'graduation_year')
    # ### end Alembic commands ###
