"""add skills column to resumes

Revision ID: e6a4857912fd
Revises: 51dec81dbef2
Create Date: 2026-09-18 19:49:48.034777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a4857912fd'
down_revision: Union[str, Sequence[str], None] = '51dec81dbef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('skills', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'skills')
    # ### end Alembic commands ###
